// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu--S-5Lt4Myn7vQZ_BtEg0s1nuKxBEPw',
    appId: '1:591311243042:web:dd80fa0acf4068e7b7c77b',
    messagingSenderId: '591311243042',
    projectId: 'final-e7ba8',
    authDomain: 'final-e7ba8.firebaseapp.com',
    storageBucket: 'final-e7ba8.firebasestorage.app',
    measurementId: 'G-ZFBS138XMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLT1rNuZK9nZgn-BPOZadhYglS3TeY4GY',
    appId: '1:591311243042:android:b570ae85869de1e7b7c77b',
    messagingSenderId: '591311243042',
    projectId: 'final-e7ba8',
    storageBucket: 'final-e7ba8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD81xPQsK2yJAQM9AyEq_I52E_IJFf0MPc',
    appId: '1:591311243042:ios:ae9dd0b8d49f326cb7c77b',
    messagingSenderId: '591311243042',
    projectId: 'final-e7ba8',
    storageBucket: 'final-e7ba8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD81xPQsK2yJAQM9AyEq_I52E_IJFf0MPc',
    appId: '1:591311243042:ios:ae9dd0b8d49f326cb7c77b',
    messagingSenderId: '591311243042',
    projectId: 'final-e7ba8',
    storageBucket: 'final-e7ba8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu--S-5Lt4Myn7vQZ_BtEg0s1nuKxBEPw',
    appId: '1:591311243042:web:78acd35d79baea80b7c77b',
    messagingSenderId: '591311243042',
    projectId: 'final-e7ba8',
    authDomain: 'final-e7ba8.firebaseapp.com',
    storageBucket: 'final-e7ba8.firebasestorage.app',
    measurementId: 'G-D8GXCBX08T',
  );
}
